-- PostgreSQL 方言。原 MySQL 版本已废弃：本项目 2026-08-09 从 MySQL 8.4 硬切到
-- PostgreSQL，目标库是全新的，没有 flyway_schema_history，因此直接改写而非新增迁移。
--
-- 与 MySQL 版的三处语义差异，改动时注意：
--   1. id 用 GENERATED BY DEFAULT AS IDENTITY 而非 ALWAYS —— 数据迁移要显式插入
--      历史主键，ALWAYS 需要 OVERRIDING SYSTEM VALUE，容易漏写。
--   2. JSON → JSONB。MyBatis 取值仍按字符串处理，读写不受影响。
--   3. MySQL 的 ON UPDATE CURRENT_TIMESTAMP 在 PG 没有等价物，靠下面的触发器补。
--      差别：MySQL 仅在行内容确实变化时更新该列，PG 触发器每次 UPDATE 都会更新。

CREATE TABLE wechat_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id VARCHAR(64) NOT NULL,
    open_id VARCHAR(128) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    raw_msg_type VARCHAR(32) NOT NULL,
    raw_event VARCHAR(64) NULL,
    message_id BIGINT NULL,
    original_occurred_at TIMESTAMP(6) NOT NULL,
    effective_occurred_at TIMESTAMP(6) NOT NULL,
    received_at TIMESTAMP(6) NOT NULL,
    anomalous_timestamp BOOLEAN NOT NULL DEFAULT FALSE,
    deduplication_key VARCHAR(71) NOT NULL,
    raw_event_key VARCHAR(512) NULL,
    qr_scene VARCHAR(512) NULL,
    ticket VARCHAR(512) NULL,
    ticket_present BOOLEAN NOT NULL DEFAULT FALSE,
    menu_key VARCHAR(512) NULL,
    menu_url VARCHAR(2048) NULL,
    latitude DECIMAL(10, 7) NULL,
    longitude DECIMAL(10, 7) NULL,
    location_precision DECIMAL(12, 6) NULL,
    composite_type VARCHAR(32) NULL,
    composite_item_count INT NULL,
    composite_sha256 CHAR(64) NULL,
    safe_summary JSONB NOT NULL,
    normalized_message_sha256 CHAR(64) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_event_dedup UNIQUE (app_id, deduplication_key)
);

CREATE INDEX ix_event_report ON wechat_event (effective_occurred_at, event_type);
CREATE INDEX ix_event_user ON wechat_event (open_id, effective_occurred_at);

CREATE TABLE daily_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_date DATE NOT NULL,
    version INT NOT NULL,
    window_start TIMESTAMP(6) NOT NULL,
    window_end TIMESTAMP(6) NOT NULL,
    data_cutoff_at TIMESTAMP(6) NOT NULL,
    snapshot_json JSONB NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_report_version UNIQUE (report_date, version)
);

CREATE TABLE report_delivery_attempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id CHAR(36) NOT NULL,
    report_id BIGINT NOT NULL,
    trigger_type VARCHAR(16) NOT NULL,
    request_id VARCHAR(128) NULL,
    -- 生成列：只有 AUTO 触发的行参与 uq_auto_report 唯一约束，MANUAL 行取 NULL。
    -- PG 与 MySQL 一致，唯一约束中多个 NULL 互不冲突。
    auto_report_id BIGINT GENERATED ALWAYS AS (
        CASE WHEN trigger_type = 'AUTO' THEN report_id ELSE NULL END
    ) STORED,
    status VARCHAR(16) NOT NULL,
    recipient_masked VARCHAR(1024) NOT NULL,
    recipient_sha256 CHAR(64) NOT NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    claimed_at TIMESTAMP(6) NULL,
    lease_until TIMESTAMP(6) NULL,
    completed_at TIMESTAMP(6) NULL,
    last_error_class VARCHAR(128) NULL,
    last_error_summary VARCHAR(500) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_delivery_id UNIQUE (delivery_id),
    CONSTRAINT uq_auto_report UNIQUE (auto_report_id),
    CONSTRAINT uq_manual_request UNIQUE (report_id, request_id),
    CONSTRAINT fk_delivery_report
        FOREIGN KEY (report_id) REFERENCES daily_report (id)
);

-- 替代 MySQL 的 ON UPDATE CURRENT_TIMESTAMP(6)。没有它，updated_at 会在第一次
-- 写入后永远停在创建时间 —— 不报错，只是数据悄悄变错，租约回收会读到错误的时间。
CREATE OR REPLACE FUNCTION lumora_set_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_delivery_updated_at
    BEFORE UPDATE ON report_delivery_attempt
    FOR EACH ROW EXECUTE FUNCTION lumora_set_updated_at();
