-- 分享 JS-SDK 签名失败上报。
--
-- 前端 wx.error / fetch 失败时，POST /wechat/callback/jsapi-signature/error
-- 把页面 URL 和微信返回的 errMsg 落库，便于回看分享卡片为什么没生效
-- （典型：公众号后台 JS 安全域名没配 lumora.love）。
--
-- PostgreSQL 方言。原 MySQL 版本随 V1/V2 一同改写，见 V1 文件头的说明。
-- received_at 全索引用于按时间排查和保留删除。
--
-- url 的索引是这次改写里唯一没有直接对应写法的地方。MySQL 原本是前缀索引
-- `INDEX ix_jsapi_error_url (url(255))`，PostgreSQL 没有前缀索引这个概念。
--
-- 实测过整列 btree 的边界（PG 17，索引项上限 2704 字节）：
--   纯 ASCII 2048 字符（2048 字节）        → 成功
--   高熵多字节 2048 字符（6144 字节）      → ERROR: index row size 6160
--                                            exceeds btree version 4 maximum 2704
-- 也就是说：真实 URL 是百分号编码的 ASCII，整列索引在实践中不会炸。这里不用它
-- 是因为这张表本身是用来记录错误的 —— 如果它的索引存在拒绝 INSERT 的可能，
-- 故障会表现为「错误上报接口返回 500」，上报错误的通道自己坏掉，最难查。
-- 表达式索引无条件有界，不留这个可能性，语义上也才真正等价于原来的前缀索引。
--
-- 代价是查询必须写成 WHERE left(url, 255) = ... 才能命中。当前应用侧没有按 url
-- 查询的语句（mapper 只有 INSERT 和按 received_at 的 DELETE），这个索引是留给
-- 人工排查用的，届时记得带上 left(...)。
CREATE TABLE jsapi_signature_error (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url VARCHAR(2048) NOT NULL,
    err_msg VARCHAR(1024) NOT NULL,
    received_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_jsapi_error_received_at ON jsapi_signature_error (received_at);
CREATE INDEX ix_jsapi_error_url ON jsapi_signature_error (left(url, 255));
