-- 正常的客户端观测事件。JS-SDK 错误继续单独保存在 jsapi_signature_error。
-- type 保持开放，事件的可变字段放 JSONB，新增事件无需修改表结构。
CREATE TABLE client_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id VARCHAR(64) NOT NULL,
    type VARCHAR(64) NOT NULL,
    url VARCHAR(2048) NOT NULL,
    properties JSONB NOT NULL DEFAULT '{}'::jsonb,
    received_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_client_event_received_at ON client_event (received_at);
CREATE INDEX ix_client_event_type_received_at ON client_event (type, received_at);
CREATE INDEX ix_client_event_visit_id ON client_event (visit_id);
CREATE INDEX ix_client_event_url ON client_event (left(url, 255));
